// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    HeadNav: typeof import('./src/components/HeadNav.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    LeftBar: typeof import('./src/components/LeftBar.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LyricsScroll: typeof import('./src/components/LyricsScroll.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    PlayControl: typeof import('./src/components/PlayControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondNavBar: typeof import('./src/components/SecondNavBar.vue')['default']
    TableList: typeof import('./src/components/TableList.vue')['default']
    UserListCard: typeof import('./src/components/UserListCard.vue')['default']
  }
}

export {}
